// Generated by CoffeeScript 1.7.1
(function() {
  var limited_infection, total_infection;

  total_infection = function() {
    return "success";
  };

  limited_infection = function() {
    return "success";
  };

  window.total_infection = total_infection;

  window.limited_infection = limited_infection;

}).call(this);
